name: test
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: build + test
        run: |
          npm ci
          npm run build
          npm test -- --passWithNoTests

      - name: prep action
        run: |
          mkdir my-site

          cat << EOF > my-site/index.html
          <!DOCTYPE html>
          <html lang="en-GB">
            <head>
              <meta charset="utf-8">
              <title>Test</title>
            </head>
            <body>
              <p>Hello, world!</p>
            </body>
          </html>
          EOF

      - uses: actions/upload-artifact@v3
        with:
          path: my-site

      - uses: ./
        with:
          app: the-coolest-static-site
          domain: test.devx.gutools.co.uk
          auth: "none"
